dist: xenial

language: python

cache: pip

env:
  - DJANGO_VERSION=2.0
  - DJANGO_VERSION=2.1
  - DJANGO_VERSION=2.2
  - DJANGO_VERSION=3.0

matrix:
  include:
    - { env: DJANGO_VERSION=2.0, python: 3.4 }
    - { env: DJANGO_VERSION=2.0, python: 3.5 }
    - { env: DJANGO_VERSION=2.0, python: 3.6 }
    - { env: DJANGO_VERSION=2.0, python: 3.7 }

    - { env: DJANGO_VERSION=2.1, python: 3.5 }
    - { env: DJANGO_VERSION=2.1, python: 3.6 }
    - { env: DJANGO_VERSION=2.1, python: 3.7 }

    - { env: DJANGO_VERSION=2.2, python: 3.5 }
    - { env: DJANGO_VERSION=2.2, python: 3.6 }
    - { env: DJANGO_VERSION=2.2, python: 3.7 }

    - { env: DJANGO_VERSION=3.0, python: 3.6 }
    - { env: DJANGO_VERSION=3.0, python: 3.7 }
    - { env: DJANGO_VERSION=3.0, python: 3.8 }

install:
  - pip install flake8
  - pip install coverage
  - pip install codecov
  - pip install Django==$DJANGO_VERSION

script:
  - flake8 ./metatags
  - coverage run runtests.py

after_success:
  - codecov
